title: bfban assistants app
description: bfban assistants app
theme: just-the-docs

port: 4003

url: https://github.com/bfban
favicon_ico: "/assets/images/logo.png"
logo: "/assets/images/logo.png"
search_enabled: true
color_scheme: main

callouts:
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: App 网站
    url: https://bfban-app.cabbagelol.net
    hide_icon: false
  - title: App 仓库
    url: https://github.com/bfban/bfban-app-mobile
    hide_icon: false
  - title: APP 文档仓库
    url: https://github.com/cabbagelol/bfban-app-mobile-docs
    hide_icon: false
  - title: BFBAN 材料设计
    url: https://github.com/BFBAN/exterior-design
    hide_icon: false


